Output ./demo/base.gif

Set FontSize 16
Set Width 800
Set Height 600
Set Padding 20
Set Margin 10
Set MarginFill "#14A07B"
Set BorderRadius 40

# Type a command in the terminal.
Type@0s "./build/minigun"
Enter
Sleep 1s

Type "jjjjjjjjjj"
Sleep 500ms
Type "lllllllllll"
Sleep 500ms
Type@100ms ":random coooommand"
Left@100ms 4
Backspace@100ms 4
Sleep 500ms
Enter
Sleep 1s
Type@100ms ":q"
Sleep 500ms
Enter
